### ISSUE TITLE
Error installing: ModuleNotFoundError: No module named 'DistUtilsExtra'

### ISSUE THREAD

**Issue by WhyAreAllTheseTaken** [trizen/oblogout-py3#7]
The following error occurred while installing:
```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from DistUtilsExtra.command import *
ModuleNotFoundError: No module named 'DistUtilsExtra'
```

Python Version: 3.8.10
Distribution: Linux Mint 20.2
Command used to execute: python3 setup.py install

**Comment by trizen** [comment]
Make sure you have `python-distutils-extra` installed. (May be named `python3-distutils-extra` on Linux Mint)

**Comment by WhyAreAllTheseTaken** [comment]
Thanks, that seems to have resolved the issue.
