### ISSUE TITLE
How to set lock on hibernate and lock on suspend on config file

### ISSUE THREAD

**Issue by jpmvferreira** [trizen/oblogout-py3#8]
Hi there, I saw from your last commit (quite a while ago, but I only updated now) which you added a new settings which are lock on hibernate and lock on suspend.

I would like to set both of these off in the configuration file, while the default is on, how would I write that in the config file?

**Comment by trizen** [comment]
Try:

```conf
disable_lock_on = hibernate,suspend
```

**Comment by jpmvferreira** [comment]
Yeah, that seems to work.
Quite curious as to how the import scheme works in here... 
Would you consider adding that information to the readme? Might be useful for future users. 
Thanks!
